#This have to be  cluster specific
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
data:
#    #important: change this if deploy to a different cluster
    cluster.name: dev-eks
    logs.region: us-west-2



---
apiVersion: v1
data:
  cluster.name: dev-eks
  http.port: "2020"
  http.server: "On"
  logs.region: us-west-2
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch